# Generated by Django 4.1.1 on 2023-02-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_gamedate_room_gamerating_room_gametitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
    ]
