# Generated by Django 4.1.1 on 2023-02-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Game',
        ),
    ]
